grid:
  filepath: "data/grid/sentinel_2_level_1c_tiling_grid.kml"
  download-url: "https://sentinel.esa.int/documents/247904/1955685/S2A_OPER_GIP_TILPAR_MPC__20151209T095117_V20150622T000000_21000101T000000_B00.kml/ec05e22c-a2bc-4a13-9e84-02d5257b09a8"
copernicus:
  search-url: "https://apihub.copernicus.eu/apihub/search"
  data-dir: "data/sentinel/raw/"
  schedule-filepath: "data/sentinel/schedule.csv"
processing:
  data-dir: "data/sentinel/processed/"
  delete-source: True